[platformio]
default_envs = esp32s3

[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_src_filter = +<safety_policy.cpp> +<command_parser.cpp> +<terminal_input.cpp>
build_flags = -std=gnu++11

[env:esp32s3]
platform = espressif32
board = lumilamp-esp32s3-n16r8
framework = arduino
monitor_speed = 115200
monitor_filters = time
lib_deps =
    https://gitee.com/ftservo/FTServo_Arduino.git#64922cda46e56b21b8c1d9e830d936a1941645ae
build_flags =
    -std=gnu++17
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
